description: 'attraction-repulsion with 3 types particles'
dataset: 'gland_SMG2-processed'

simulation:
  has_fluo: True
  fluo_path: '/groups/wang/wanglab/GNN/240408-LVpD80-E10-IAI/SMG2-processed/masks/'
  fluo_method: 'add'
  params: [[-1]]
  min_radius: 0
  max_radius: 5
  n_neighbors: 10
  n_particles: 300000
  n_particle_types: 10
  n_frames: 149
  delta_t: 1
  boundary: 'no'

graph_model:
  particle_model_name: 'PDE_A'
  mesh_model_name: ''
  prediction: 'first_derivative'
  input_size: 9
  output_size: 2
  hidden_dim: 128
  n_mp_layers: 5
  aggr_type: 'mean'
  embedding_dim: 2
  update_type: 'none'

plotting:
  colormap: 'tab10'
  arrow_length: 2

training:
  n_epochs: 20
  batch_size: 1
  small_init_batch_size: False
  n_runs: 2
  sparsity: 'replace_embedding_function'
  cluster_method: 'distance_plot'
  rotation_augmentation: True
  data_augmentation_loop: 100
  fix_cluster_embedding: True
  device: 'auto'





