description: 'idem c14 coeff_missing_activity: 0.5'
dataset: 'CElegans_c1'
data_folder_name: '/groups/saalfeld/home/allierc/Py/wormvae/data/worm_activity/all_traces_Heads_new.mat'
connectome_folder_name: '/groups/saalfeld/home/allierc/Py/wormvae/data/worm_connectivity/'

simulation:
    connectivity_file: 'random'
    adjacency_matrix: ''
    connectivity_init: [0,0.1]
    connectivity_distribution: 'Lorentz'
    params: [[10.0,1.0,1.0,1.0],[10.0,2.0,1.0,2.0],[10.0,1.0,2.0,4.0],[10.0,2.0,2.0,8.0]]
    phi: 'tanh'
    tau: 1.0
    min_radius: 1.0
    max_radius: 1.0E6
    n_particles: 300
    n_particle_types: 4
    n_frames: 958
    delta_t: 0.25
    dpos_init:  0
    boundary: 'no'
    start_frame: -1000
    baseline_value: 6

graph_model:
    signal_model_name: 'PDE_N8'
    particle_model_name: ''
    mesh_model_name: ''
    prediction: 'first_derivative'
    field_type: ''

    input_size: 6
    output_size: 1
    hidden_dim: 256
    n_layers: 5

    input_size_update: 8
    hidden_dim_update: 64
    n_layers_update: 5
    output_size_update: 1

    input_size_excitation: 5
    n_layers_excitation: 3
    hidden_dim_excitation: 64

    input_size_nnr: 1
    n_layers_nnr: 5
    hidden_dim_nnr: 256
    output_size_nnr: 300
    omega: 30

    aggr_type: 'add'
    embedding_dim: 2

    update_type: 'generic_excitation'
    excitation_dim: 3

    lin_edge_positive: True

plotting:
    colormap: 'tab20'
    arrow_length: 1
    xlim: [4,8]
    ylim: [-0.1,1.0]

training:
    n_epochs: 20
    batch_size: 32
    small_init_batch_size: False
    device: 'auto'
    n_runs: 21

    multi_connectivity: True
    with_connectivity_mask: True
    has_missing_activity: True

    time_step: 8
    embedding_trial: False

    sparsity: 'none'
    rotation_augmentation: False
    data_augmentation_loop: 1500

    learning_rate_W_start: 1.0E-3

    learning_rate_start: 1.0E-4
    learning_rate_embedding_start: 1.0E-4

    learning_rate_NNR: 1.0E-5
    learning_rate_missing_activity: 1.0E-4

    coeff_edge_diff: 1
    coeff_sign : 0
    coeff_missing_activity: 0.5
    coeff_update_msg_diff: 1
    coeff_update_u_diff: 0
